#!name=腾讯文档去广告
#!desc=移除开屏广告、首页横幅推广
#!author=可莉🅥
#!icon=https://raw.githubusercontent.com/luestr/IconResource/main/App_icon/120px/TXDocs.png
#!category=广告拦截
#!link=https://apps.apple.com/app/id1370780836
#!tag=腾讯文档,去广告

[rewrite_local]
# 拦截开屏广告
^https:\/\/tianshu\.qq\.com\/open\/ts_access\/GetAds\? url script-response-body tencent_docs_ad.js

# 拦截首页横幅推广
^https:\/\/h5\.qzone\.qq\.com\/p\/adboss\/api\/json\/ts_access\/GetAds$ url script-response-body tencent_docs_ad.js

[mitm]
hostname = tianshu.qq.com, h5.qzone.qq.com

[task_local]
# 无远程任务

[script]
tencent_docs_ad.js = function(){
    $done({ body: "{}" });
}();